### ISSUE TITLE
Is it possible to have a spatial subset?

### ISSUE THREAD

**Issue by FelipeSBarros** [ecmwf/ecmwf-api-client#13]
Dear devs. Thanks for developing this API.
I am working with CAMS NRT data and realized that in the web [data retriever](https://apps.ecmwf.int/datasets/data/cams-nrealtime/levtype=sfc/) it is possible to get a spatial subset for both: already preset subset or considering a bounding box defined by user) like image below:
![image](https://user-images.githubusercontent.com/7208674/108071479-88caa100-7044-11eb-908c-0c486af3644d.png)
And this is the same for the spatial resolution:
![image](https://user-images.githubusercontent.com/7208674/108071684-c62f2e80-7044-11eb-887c-d0f17fe95918.png)

Is it possible to have any kind of spatial subset on using ecmwf-api?
And about choosing the spatial resolution (grid size)?

Thanks in advance

**Comment by cristian-codorean** [comment]
Hi @FelipeSBarros, use a `grid` and / or `area` definition as in the example below:
```
#!/usr/bin/env python
from ecmwfapi import ECMWFDataServer
server = ECMWFDataServer()
server.retrieve({
    "class": "mc",
    "dataset": "cams_nrealtime",
    "date": "2021-02-01/to/2021-02-11",
    "expver": "0001",
    "levtype": "sfc",
    "param": "167.128",
    "step": "24",
    "stream": "oper",
    "time": "00:00:00",
    "type": "fc",
    "area": "73.5/-27/33/45", # Europe
    "grid": "0.4/0.4",
    "target": "output",
})
```
Some documentation on the format of `grid` and `area` at https://confluence.ecmwf.int/pages/viewpage.action?pageId=151520973.

**Comment by FelipeSBarros** [comment]
Thanks @cristian-codorean ! I have just found the FAQ web page. I was trying to find the documentation, but seems that everything I need to know is there. Thanks again!
