### ISSUE TITLE
Is this repo still in use?

### ISSUE THREAD

**Issue by paapu88** [ecmwf/ecmwf-api-client#20]
Dear Developers,
Is this repo still in use for retrieving data from ecmwf?

I tried instructions in 
https://pypi.org/project/ecmwf-api-client/

to "Register with ECMWF "

Problem: there is no such www page as 
 https://apps.ecmwf.int/registration/
 
 So if this repo is out of date could you please delete it?
 
 Cheers, Markus

**Comment by snow73** [comment]
I am not a developer of this library but a user and can confirm that it still works. I think just the links to register and login have change and the documentation should be adjusted. Maybe you check out https://accounts.ecmwf.int/auth/realms/ecmwf/login-actions/registration?client_id=apps&tab_id=0Au0D5tw1-A

p.s.: The README.md of the repository has already been updated in that respect (https://github.com/ecmwf/ecmwf-api-client/commit/3f4baf3e211661c056b6b31598f775d9bf96a2d2)

**Comment by paapu88** [comment]
Thanks for updating the README.md with correct links!

Can confirm it works and available datasets for me as a member of public are:
1) S2S: https://apps.ecmwf.int/datasets/data/s2s-realtime-instantaneous-accum-ecmf/
2) TIGGE: https://apps.ecmwf.int/datasets/data/tigge/levtype=sfc/type=cf/

Unfortunately these were not the ones I was looking for.


 See also https://apps.ecmwf.int/datasets/
